imu:
  - id: 0
    description: "imu"
    url: "rtsp://192.168.1.6/video1"
    priority: 7
    task_type:
      - type_name: "imu"
        default: true
        pipeline:
          - service_name: "imu-trajectory-sensing"
