imu:
  - id: 0
    description: "imu"
    url: "http://192.168.1.6:5000/imu"
    priority: 7
    task_type:
      - type_name: "imu"
        default: true
        pipeline:
          - service_name: "imu-trajectory-sensing"
