video:
  - id: 1
    description: "car"
    resolution: "1080p"
    fps: 30
    url: "rtsp://192.168.1.6/video1"
    priority: 7
    task_type:
      - type_name: "car"
        default: true
        pipeline:
          - service_name: "car-detection"
          - service_name: "license-plate-detection"
      - type_name: "human"
        default: false
        pipeline:
          - service_name: "car-detection"