
apiVersion: sedna.io/v1alpha1
kind: JointMultiEdgeService
metadata:
  name: car-detection-service
  namespace: auto-edge
spec:
  edgeWorker:
    - file:
        path: "/home/nvidia/zwh/Auto-Edge/model_lib"
      kubeConfig:
        path: "/home/nvidia/.kube"
      logLevel:
        level: "DEBUG"
      template:
        spec:
          nodeName: edge1
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - image: onecheck/car-detection:arm64-mid-v1.0.0
            imagePullPolicy: IfNotPresent
            name: car-detection
            env:
              - name: controller_port
                value: "39200"
              - name: max_queue_size
                value: "5"
            ports:
              - containerPort: 9001
                hostPort: 39001
    - file:
        path: "/home/nvidia/zwh/Auto-Edge/model_lib"
      kubeConfig:
        path: "/home/nvidia/.kube"
      logLevel:
        level: "DEBUG"
      template:
        spec:
          nodeName: edge2
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - image: onecheck/car-detection:arm64-mid-v1.0.0
            imagePullPolicy: IfNotPresent
            name: car-detection
            env:
              - name: controller_port
                value: "39200"
              - name: max_queue_size
                value: "5"
            ports:
              - containerPort: 9001
                hostPort: 39001
  cloudWorker:
    file:
      path: "/home/hx/zwh/Auto-Edge/model_lib"
    kubeConfig:
      path: "/home/hx/.kube"
    template:
      spec:
        nodeName: cloud.kubeedge
        dnsPolicy: ClusterFirstWithHostNet
        containers:
          - image: onecheck/car-detection:mid-v1.0.0
            name:  car-detection
            imagePullPolicy: IfNotPresent
            env:
              - name: controller_port
                value: "39200"
              - name: max_queue_size
                value: "5"
            ports:
              - containerPort: 9001
                hostPort: 39001
